### ISSUE TITLE
Text only renders before cursor when launched from Powershell

### ISSUE THREAD

**Issue by ghost** [linde12/kod#10]
Built on Windows and opened the same file (`kod.go`) in both `Visual Studio Code` and `kod` launched from `Powershell`.  The screenshot is from the builtin terminal in `VS Code`, but I get the same result in a standalone `Powershell` window.

In the following screenshot the cursor is in the same position in both panes, on line 16 (15 in `kod`).  You can see that the rest of the file past the cursor does not render in `kod`.  The entire file is rendered on first load, but as soon as the cursor is moved the rest of the file disappears.

Additionally, there is noticeable flicker whenever the cursor moves.

![image](https://user-images.githubusercontent.com/20893484/38466180-55a0029c-3ae2-11e8-87f3-f8e1a0533907.png)

**Comment by ghost** [comment]
Using `^s` to save the file will cause another screen flicker, but will show the entire file as though the editor was relaunched.  Moving the cursor again removes the rest of the file.

**Comment by linde12** [comment]
This is related to issue #7 and has something to do with the linecache's `ApplyUpdate` method. The core has finished/changed the protocol for line invalidation so i imagine this is where the problem lies.

**Comment by ghost** [comment]
Thanks for the quick response!

That sounds like exactly what's causing this, sorry for the duplicate issue.

I'm just trying to figure out what UI to run on Windows to hack about in `xi`, haven't spent too long looking around.  Seems odd that moving the cursor would trigger an invalidation for everything afterward, since most editors don't reflow the text around the cursor's position or anything like that.  I'll have to look into why that is...
