### ISSUE TITLE
Fix the "update" case in linecache.go and remove the addLines method

### ISSUE THREAD

**Issue by linde12** [linde12/kod#12]
We're not entirely sure when "update" is called, but i'm guessing it's when e.g. a third party plugin will do some changes to the code. E.g. syntect.

Essentially it's not sure whether "update" works or not and we want to remove the use of the `addLines` method so that we can remove it completely.

**Comment by cmyr** [comment]
Sorry, commented in the PR but here is probably better:

`update` is intended  as an optimization in the case where styles or cursors have changed, but the text contents of a line have not. This is not directly related to plugins, although in  theory it would be used if, (for instance) highlighting was enabled or disabled.

It is not currently used.

**Comment by linde12** [comment]
@cmyr OK! Thanks for the reply :smiley:

**Comment by sjoshid** [comment]
@linde12 
Since it is not used, should I go ahead and do some cleanup? No point in keeping dead code. Unless you think otherwise.

**Comment by linde12** [comment]
@sjoshid Go ahead if you are feeling up for it it'd be great!

**Comment by linde12** [comment]
Closed by #14
