### ISSUE TITLE
only works in xterm

### ISSUE THREAD

**Issue by nkoehring** [linde12/kod#18]
kod startup failes with `terminal entry not found` in [st](http://st.suckless.org/) even before telling me that I forgot the file name. I tried xterm, where it works as expected, and urxvt, where it starts but has lots of rendering issues.
I didn't try fancy GTK or QT based terminal emulators.

**UPDATE:** Related to https://github.com/gdamore/tcell/issues/118 . As soon as I change `$TERM` accordingly, it works.

**Comment by linde12** [comment]
Sweet! I've actually only tried urxvt, xterm and termite. Nice find.

**Comment by linde12** [comment]
Closing this for now, let's reopen if it's still an issue for people.
