### ISSUE TITLE
Closing with Ctrl+Q makes the terminal glitch

### ISSUE THREAD

**Issue by emigr2k1** [linde12/kod#24]
When you use Ctrl+Q to close Kod, the terminal looks bad. So bad.
Using F1 works as expected.

[Video showing what I mean](https://streamable.com/0lil7)

[Here](https://github.com/linde12/kod/blob/ec5832ded30241e9cd78489d86f7d1b95b38291b/editor/editor.go#L187) when you press F1 Kod calls close() and then kod finishes the editor.
[Here](https://github.com/linde12/kod/blob/ec5832ded30241e9cd78489d86f7d1b95b38291b/editor/view.go#L169) But when you press Ctrl+Q, Kod only calls os.Exit()

I can send a pull request., but I would like to know how it should be done.

If I'm not wrong, F1 is to exit the whole editor and Ctrl+Q is to close the current view but for now we can only have 1 view, right? If so, do you think that they should do the same thing until Kod supports multiple views (if it will)?

**Comment by linde12** [comment]
Yeah i think i just put `os.Exit()` instead of a panic or something, so i agree with you that Ctrl+Q & F1 should be the same at the moment. Maybe we could remove F1 as well, because it makes no sense - i think i just implemented it during early development to be able to exit cleanly.

Thanks for all your help @emigr2k1

**Comment by emigr2k1** [comment]
So should we remove F1 and implement its functionality to Ctrl+Q which is the key that causes this issue?

I'll try to send a PR soon, if someone else haven't already.

By the way, have you thought in implementing config files for different things like keybinds? I would like to know if you have plans for the future of this project.

You're welcome. I like this project and would like to contribute more to its development. :D

**Comment by linde12** [comment]
Yeah, lets do that :smile: 

And regarding the config files: Yes, but last time i checked xi was too early in development (imo) to start implementing user configs. Now i think Xi has its own config system and that is what should be using.

Eventually i want kod to become a "vim-like" client to rust and i'm hoping that we can rely much on xi-core to handle keybinds (See https://github.com/xi-editor/xi-editor/issues/302#issuecomment-319663662)

But for now i think we should rely on Xi's config and request it on startup to implement user configs! I'll create an empty issue for it.

**Comment by sixtyfive** [comment]
Not sure if this helps, but also calling `kod` without an input file (my first attempt to open it) will cause the terminal to glitch, requiring a `reset`.

**Comment by linde12** [comment]
@sixtyfive Yeah currently only editing works, not creating new files. I haven't implemented a command line interface like in vim (e.g. `:w file.rs`)

Feel free to add an issue about it so we can track it!
