### ISSUE TITLE
Doesn't build as per the README's instructions

### ISSUE THREAD

**Issue by sixtyfive** [linde12/kod#27]
```
user@machine ~ $ git clone https://github.com/linde12/kod.git
[...]
user@machine ~ $ cd kod
user@machine ~/kod $ which xi-core
/home/user/.cargo/bin/xi-core
user@machine ~/kod $ go build
kod.go:10:2: cannot find package "github.com/linde12/kod/editor" in any of:
	/usr/lib64/golang/src/github.com/linde12/kod/editor (from $GOROOT)
	/home/user/go/src/github.com/linde12/kod/editor (from $GOPATH)
user@machine ~/kod $
```

Are the instructions missing anything or am I doing something wrong?

**Comment by linde12** [comment]
Hey @sixtyfive i built it yesteday so i think this is an environment problem.

Is both GOPATH & GOROOT environment variables set? Did you `go get` the program?

Make sure that those are set and then try `go get github.com/linde12/kod`, navigate to the directory and run `go build` again.

**Comment by sixtyfive** [comment]
Ah, it turned out that my distribution had set neither and I had to make sure that `GOROOT` was kept unset and `GOPATH` was set to somewhere that I wanted to keep things `go get` downloads. Thanks for sending me the right (go)path!
