### ISSUE TITLE
kod not found in path

### ISSUE THREAD

**Issue by ClayMav** [linde12/kod#3]
```
/Users/maverick/xi-editor/rust/target/debug/xi-core:/Users/maverick/go¬/bin:/Users/maverick/go/bin:/Users/maverick/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/opt/X11/bin¬:/Users/maverick/Library/Android/sdk/tools:/Users/maverick/Library/Android/sdk/platform-tools
```
Above is my $PATH, but every time I run `kod` it tells me that "xi-core" is not in PATH. Not sure what is the problem. From my understanding of exec.LookPath, this should not be happening, as it should be checking $PATH

I am on MacOS.

**Comment by linde12** [comment]
Ah, i see. Are you able to start the core by running `xi-core`? It looks like you included the binary itself in the PATH variable.

I think this `/Users/maverick/xi-editor/rust/target/debug/xi-core` should become this `/Users/maverick/xi-editor/rust/target/debug`

xi-core recently changed how they handle document invalidation so AFAIK `kod` isn't working properly when it renders the document. I've been busy lately but a pull request would be welcome if you're up for the task.
