### ISSUE TITLE
Separate default keybinds per platform

### ISSUE THREAD

**Issue by emigr2k1** [linde12/kod#37]
The default keybinds to move per word, move to the start/end of line, etc. Are different in each platform, at least on windows and mac.

If Kod is still going to use "normal" keybinds (arrows to move, ctrl-s to save), it should make sense to make the default keybinds the same of their respective platforms. This should be impossible for mac because of "cmd" key but "ctrl" could be used instead.

This shouldn't be hard to do, at least until there is another way to handle input like a vim-like plugin.

**Comment by linde12** [comment]
See my reply for #43 I think same goes for this

**Comment by emigr2k1** [comment]
Closing because there's another issue (#43) which discuss the same.
