### ISSUE TITLE
Cannot do go build

### ISSUE THREAD

**Issue by meain** [linde12/kod#38]
```
./kod.go:46:23: too many arguments in call to editor.NewEditor
        have (readwriter, string)
        want (io.ReadWriter)
```

Seems like some changes where done in commit https://github.com/linde12/kod/commit/cebc8591#diff-a4099a04e355d56f90cecf992fc01a06L52. But the signature is still wrong for editor.NewEditor.

Am I doing something wrong?

**Comment by emigr2k1** [comment]
That commit is from a year ago. Try updating kod using:
```bash
go get -u github.com/linde12/kod
```

**Comment by meain** [comment]
I actually did a git clone. Not sure what happened. Did work with this tough.
