### ISSUE TITLE
Some runes use more than 8bytes and is rendered with a space after

### ISSUE THREAD

**Issue by jantb** [linde12/kod#41]
Try typing æøå into the editor.

**Comment by linde12** [comment]
Weird, this should be accounted for. I remember specifically implementing support for some weird unicode characters and chinese characters. We will have to look into it! Thanks :smile:

**Comment by jantb** [comment]
Try inserting them into a line with text and press left and right arrow.

**Comment by linde12** [comment]
Just looked into this and i guess i don't really have that commit :confused: I think for the cursor placement something like this should work. In util.go:

```diff
 func GetCursorVisualX(x int, line string) int {
-	r := []rune(line)
-	if x > len(r) {
-		x = len(r) - 1
+	if x > len(line) {
+		x = len(line) - 1
 	}
 
-	return ByteWidth(string(r[:x]), tabSize)
+	return ByteWidth(string(line[:x]), tabSize)
 }
```

As for full unicode support (fullwidth characters and such) view.go needs a bigger rewrite. tcell has a nice example of how unicode could be handled if anyone wants to give it as stab. Here's the link https://github.com/gdamore/tcell/blob/master/_demos/unicode.go

Right now we naively expect that 1 character = 1 rune but some runes are combination runes. See signature of tcell's `SetContent`, we have to use the combc argument.

**Comment by jantb** [comment]
Thanks a lot, this solves my issue at least, and probably for most other western characters like ß and ö.
Are you going to commit the change?

**Comment by linde12** [comment]
You wanna do it @jantb? Othetwisw i'll do it later in the week i think :smile:

**Comment by jantb** [comment]
sure, np
