### ISSUE TITLE
Only partial text gets pasted

### ISSUE THREAD

**Issue by ritiek** [linde12/kod#48]
When copying some text from outside and pasting it in `kod`, some characters and words are skipped.

Does anyone face a similar problem? I tried this with gnome-terminal and xterm with latest commit on xi core repository (https://github.com/xi-editor/xi-editor/commit/25d2a72af0d2f13372e5b3a700653f749418c8b6).

**Comment by linde12** [comment]
That might be a bug, i haven't tried copy-pasting myself
