### ISSUE TITLE
stupid question

### ISSUE THREAD

**Issue by drandreaskrueger** [linde12/kod#49]
installation went smoothly, kudos for that.

now I have numbered lines, and I can type, but that's it. Oh, the cursor keys work too.     

but ... I need a howto for dummies: key combination to e.g. save, quit, mark-copy-paste, etc. ?

not even Ctrl-c does anything anymore.

thanks!

**Comment by linde12** [comment]
Hi, im not actively working on kod anymore and i wont be, at least until xi is more stable. Even if it does become stable anytime soon and i do start to code on it again, i might completely switch to using rust instead.
