### ISSUE TITLE
linecache invalidation is not up to date with xi-core

### ISSUE THREAD

**Issue by linde12** [linde12/kod#7]
The core introduced a breaking change and i haven't had the time to update kod yet.

I think this can be fixed somewhere in the ApplyUpdate method in editor/linecache.go

There are a few editors which have implemented this already. I believe xi-tui(rust) amongst other should work with the latest version. There is also some documentation about this in the xi-editor project.

**Comment by sjoshid** [comment]
Let me try to fix this. I see some changes that need to be applied to ApplyUpdate.

**Comment by linde12** [comment]
@sjoshid Sure thing! I haven't looked into exactly what's causing the rendering to go bad, but i'm pretty sure it has to do with ApplyUpdate as well. Tell me if you need anything.

**Comment by sjoshid** [comment]
@linde12 
I assume [this](https://gph.is/2JxPlbV) is the issue referring to.

**Comment by linde12** [comment]
Yes @sjoshid, exactly

**Comment by sjoshid** [comment]
Great. I have already fixed it. Doing some final testing. I'll commit probably after I get home from work.

**Comment by linde12** [comment]
Awesome! Maybe soon we'll back to having the editor be compatible with xi-editor@master :-)

**Comment by linde12** [comment]
I think we can close this thanks to #11 but there are still problems with the editor. Especially how the last lines and the line numbers behave. I will make separate issues.
